<a href="https://colab.research.google.com/github/mirraaditiir2025cse-cpu/FDS-CS23334-all-Lab-Experiments/blob/main/FDS_Lab_experiment_20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
list=[[1,'Smith',50000],[2,'Jones',60000]]
df=pd.DataFrame(list)
df

   0      1      2
0  1  Smith  50000
1  2  Jones  60000

In [ ]:
df.columns=['Empd','Name','Salary']
df

   Empd   Name  Salary
0     1  Smith   50000
1     2  Jones   60000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Empd    2 non-null      int64
 1   Name    2 non-null      object
 2   Salary  2 non-null      int64
dtypes: int64(2), object(1)
memory usage: 180.0+ bytes

In [ ]:
df=pd.read_csv("/content/employee_dataset.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee ID  7 non-null      object
 1   First Name   7 non-null      object
 2   Last Name    7 non-null      object
 3   Email        7 non-null      object
 4   Department   7 non-null      object
 5   Job Title    7 non-null      object
 6   Hire Date    7 non-null      object
 7   Salary       7 non-null      int64
 8   Status       7 non-null      object
dtypes: int64(1), object(8)
memory usage: 636.0+ bytes

In [ ]:
df.head()

,Employee ID,First Name,Last Name,Email,Department,Job Title,Hire Date,Salary,Status
0,EMP001,John,Doe,john.doe@company.com,Engineering,Software Engineer,2022-03-15,85000,Active
1,EMP002,Jane,Smith,jane.smith@company.com,Marketing,Specialist,2021-06-01,62000,Active
2,EMP003,Michael,Brown,michael.b@company.com,Sales,Account Manager,2023-01-10,70000,Active
3,EMP004,Emily,Davis,emily.davis@company.com,Human Resources,HR Generalist,2020-11-04,65000,Active
4,EMP005,David,Wilson,david.w@company.com,Engineering,QA Lead,2019-08-22,92000,Terminated

In [ ]:
df.tail()

,Employee ID,First Name,Last Name,Email,Department,Job Title,Hire Date,Salary,Status
2,EMP003,Michael,Brown,michael.b@company.com,Sales,Account Manager,2023-01-10,70000,Active
3,EMP004,Emily,Davis,emily.davis@company.com,Human Resources,HR Generalist,2020-11-04,65000,Active
4,EMP005,David,Wilson,david.w@company.com,Engineering,QA Lead,2019-08-22,92000,Terminated
5,EMP006,Sarah,Martinez,sarah.m@company.com,Finance,Financial Analyst,2024-05-18,75000,Active
6,EMP007,James,Taylor,james.t@company.com,Support,Customer Success,2023-07-19,50000,On Leave

In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv("/content/employee_dataset.csv")
df.head()

,Employee ID,First Name,Last Name,Email,Department,Job Title,Hire Date,Salary,Status
0,EMP001,John,Doe,john.doe@company.com,Engineering,Software Engineer,2022-03-15,85000,Active
1,EMP002,Jane,Smith,jane.smith@company.com,Marketing,Specialist,2021-06-01,62000,Active
2,EMP003,Michael,Brown,michael.b@company.com,Sales,Account Manager,2023-01-10,70000,Active
3,EMP004,Emily,Davis,emily.davis@company.com,Human Resources,HR Generalist,2020-11-04,65000,Active
4,EMP005,David,Wilson,david.w@company.com,Engineering,QA Lead,2019-08-22,92000,Terminated

In [ ]:
df.tail()

,Employee ID,First Name,Last Name,Email,Department,Job Title,Hire Date,Salary,Status
2,EMP003,Michael,Brown,michael.b@company.com,Sales,Account Manager,2023-01-10,70000,Active
3,EMP004,Emily,Davis,emily.davis@company.com,Human Resources,HR Generalist,2020-11-04,65000,Active
4,EMP005,David,Wilson,david.w@company.com,Engineering,QA Lead,2019-08-22,92000,Terminated
5,EMP006,Sarah,Martinez,sarah.m@company.com,Finance,Financial Analyst,2024-05-18,75000,Active
6,EMP007,James,Taylor,james.t@company.com,Support,Customer Success,2023-07-19,50000,On Leave

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee ID  7 non-null      object
 1   First Name   7 non-null      object
 2   Last Name    7 non-null      object
 3   Email        7 non-null      object
 4   Department   7 non-null      object
 5   Job Title    7 non-null      object
 6   Hire Date    7 non-null      object
 7   Salary       7 non-null      int64
 8   Status       7 non-null      object
dtypes: int64(1), object(8)
memory usage: 636.0+ bytes

In [ ]:
df.Salary

0    85000
1    62000
2    70000
3    65000
4    92000
5    75000
6    50000
Name: Salary, dtype: int64

In [ ]:
type(df.Salary)

pandas.core.series.Series

In [ ]:
df.Salary.mean()

np.float64(71285.71428571429)

In [ ]:
df.Salary.median()

70000.0

In [ ]:
df.Salary.mode()

0    50000
1    62000
2    65000
3    70000
4    75000
5    85000
6    92000
Name: Salary, dtype: int64

In [ ]:
df.Salary.var()

201904761.90476188

In [ ]:
df.Salary.std()

14209.31954404439

In [ ]:
df.describe()

             Salary
count      7.000000
mean   71285.714286
std    14209.319544
min    50000.000000
25%    63500.000000
50%    70000.000000
75%    80000.000000
max    92000.000000

In [ ]:
df.describe(include='all')

,Employee ID,First Name,Last Name,Email,Department,Job Title,Hire Date,Salary,Status
count,7,7,7,7,7,7,7,7.000000,7
unique,7,7,7,7,6,7,7,NaN,3
top,EMP001,John,Doe,john.doe@company.com,Engineering,Software Engineer,2022-03-15,NaN,Active
freq,1,1,1,1,2,1,1,NaN,5
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71285.714286,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14209.319544,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50000.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63500.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70000.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80000.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92000.000000,NaN

In [ ]:
empCol=df.columns
empCol

Index(['Employee ID', 'First Name', 'Last Name', 'Email', 'Department',
       'Job Title', 'Hire Date', 'Salary', 'Status'],
      dtype='object')

In [ ]:
emparray=df.values
emparray

array([['EMP001', 'John', 'Doe', 'john.doe@company.com', 'Engineering',
        'Software Engineer', '2022-03-15', 85000, 'Active'],
       ['EMP002', 'Jane', 'Smith', 'jane.smith@company.com', 'Marketing',
        'Specialist', '2021-06-01', 62000, 'Active'],
       ['EMP003', 'Michael', 'Brown', 'michael.b@company.com', 'Sales',
        'Account Manager', '2023-01-10', 70000, 'Active'],
       ['EMP004', 'Emily', 'Davis', 'emily.davis@company.com',
        'Human Resources', 'HR Generalist', '2020-11-04', 65000,
        'Active'],
       ['EMP005', 'David', 'Wilson', 'david.w@company.com',
        'Engineering', 'QA Lead', '2019-08-22', 92000, 'Terminated'],
       ['EMP006', 'Sarah', 'Martinez', 'sarah.m@company.com', 'Finance',
        'Financial Analyst', '2024-05-18', 75000, 'Active'],
       ['EMP007', 'James', 'Taylor', 'james.t@company.com', 'Support',
        'Customer Success', '2023-07-19', 50000, 'On Leave']],
      dtype=object)

In [ ]:
employee_DF=pd.DataFrame(emparray,columns=empCol)
employee_DF

,Employee ID,First Name,Last Name,Email,Department,Job Title,Hire Date,Salary,Status
0,EMP001,John,Doe,john.doe@company.com,Engineering,Software Engineer,2022-03-15,85000,Active
1,EMP002,Jane,Smith,jane.smith@company.com,Marketing,Specialist,2021-06-01,62000,Active
2,EMP003,Michael,Brown,michael.b@company.com,Sales,Account Manager,2023-01-10,70000,Active
3,EMP004,Emily,Davis,emily.davis@company.com,Human Resources,HR Generalist,2020-11-04,65000,Active
4,EMP005,David,Wilson,david.w@company.com,Engineering,QA Lead,2019-08-22,92000,Terminated
5,EMP006,Sarah,Martinez,sarah.m@company.com,Finance,Financial Analyst,2024-05-18,75000,Active
6,EMP007,James,Taylor,james.t@company.com,Support,Customer Success,2023-07-19,50000,On Leave